# Generated by Django 4.1.7 on 2023-03-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion', models.CharField(max_length=250)),
                ('prioridad', models.CharField(choices=[('1', '1-URGENTE'), ('2', '2-Importante'), ('3', '3-Normal'), ('4', '4-Programado')], default=3, max_length=1)),
            ],
        ),
    ]
