# Generated by Django 4.1.7 on 2023-03-14 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='fecha_solicitud',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
