# Generated by Django 4.0 on 2023-03-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_tickets_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
