# Generated by Django 4.0 on 2023-03-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0008_alter_empresas_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='levanta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
