# Generated by Django 4.0 on 2023-03-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_tickets_levanta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='levanta',
            new_name='levanta_ticket',
        ),
    ]
