# Generated by Django 4.0 on 2023-03-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_rename_levanta_tickets_levanta_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='cliente_solicita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sucursal', to='tickets.empresas'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='levanta_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_empresa', to='tickets.empresas'),
        ),
    ]
