# Generated by Django 4.0 on 2023-03-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_tickets_cliente_solicita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='cliente_solicita',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='levanta_ticket',
        ),
    ]
