# Generated by Django 4.0 on 2023-03-19 19:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0012_remove_tickets_cliente_solicita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='levanta_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levanta', to='auth.user'),
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.empresas')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
