# Generated by Django 4.0 on 2023-03-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_tickets_cliente_solicita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
