# Generated by Django 4.0 on 2023-03-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0020_alter_tickets_cliente_solicita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='levanta_ticket',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'director general'), ('groups__name', 'director operativo'), ('groups__name', 'creativo'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levanta', to='auth.user'),
        ),
    ]
