# Generated by Django 4.0 on 2023-03-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0022_tickets_apoyo_tickets_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='apoyo',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'creativo')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoyo', to='auth.user'),
        ),
    ]
