# Generated by Django 4.0 on 2023-03-20 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_alter_tickets_apoyo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='informacion',
            new_name='peticion',
        ),
        migrations.AddField(
            model_name='tickets',
            name='correcciones',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tickets',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.empresas'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='fecha_entrega',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='fecha_limite',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='info_cliente',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tickets',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tickets',
            name='servidor_ubicacion',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
