# Generated by Django 4.0 on 2023-03-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_rename_informacion_tickets_peticion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='duracion',
            field=models.CharField(blank=True, choices=[('1', 'Una Sola Vez'), ('2', 'Todo el Mes'), ('3', 'Hasta FIN DE MES'), ('4', 'Hasta la fecha del Evento'), ('5', 'Una vez al Mes'), ('6', 'Dos veces al Mes'), ('7', 'Una semana'), ('8', 'Hasta teminar Material')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='error',
            field=models.CharField(blank=True, choices=[('1', 'No aprobado por Cliente'), ('2', 'Extemporaneo'), ('3', 'Uso de material indebido'), ('4', 'Error ortográfico o de dedo'), ('5', 'Información erronea')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('1', 'Una Sola Vez'), ('2', '1 vez a la semana'), ('3', '2 vez a la semana'), ('4', '3 vez a la semana'), ('5', 'Diario'), ('6', 'Lunes a Viernes'), ('7', 'Una vez al Mes'), ('8', 'Lunes a Sábado')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tipo_error',
            field=models.CharField(blank=True, choices=[('1', 'Ortográfico'), ('2', 'Diseño'), ('3', 'Material Equivocado'), ('4', 'Sticker/Ticket en Whats'), ('5', 'Etiquetas Barrido'), ('6', 'Priorización'), ('7', 'Registro de Actividades')], max_length=2, null=True),
        ),
    ]
