# Generated by Django 4.0 on 2023-05-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_alter_tickets_duracion_alter_tickets_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='prioridad',
            field=models.CharField(choices=[('1', 'URGENTE'), ('2', 'Importante'), ('3', 'Normal'), ('4', 'Programado')], default=3, max_length=10),
        ),
    ]
