# Generated by Django 4.0 on 2023-05-23 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0026_remove_empresas_correo_remove_empresas_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrilas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrilla', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('copy', models.CharField(max_length=100)),
                ('frase', models.CharField(max_length=100)),
                ('nuevo', models.CharField(max_length=100)),
                ('republicacion', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('tipos_contenido', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('elaborado', models.CharField(max_length=100)),
                ('ticket', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tickets',
            name='apoyo',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'DO'), ('groups__name', 'creativo'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoyo', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='encargado',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'DO'), ('groups__name', 'creativo'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='levanta_ticket',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'DG'), ('groups__name', 'DO'), ('groups__name', 'creativo'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levanta', to='auth.user'),
        ),
    ]
