# Generated by Django 4.0 on 2023-05-27 14:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0027_parrilas_alter_tickets_apoyo_alter_tickets_encargado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrilla', models.CharField(max_length=100)),
                ('mes', models.CharField(blank=True, choices=[('1', 'ENERO'), ('2', 'FEBRERO'), ('3', 'MARZO'), ('4', 'ABRIL'), ('3', 'MAYO'), ('4', 'JUNIO'), ('3', 'JULIO'), ('4', 'AGOSTO'), ('3', 'SEPTIEMBRE'), ('4', 'OCTUBRE'), ('3', 'NOVIMEBRE'), ('4', 'DICIEMBRE')], max_length=2, null=True)),
                ('tipo_error', models.CharField(blank=True, choices=[('1', 'Ortográfico'), ('2', 'Diseño'), ('3', 'Material Equivocado'), ('4', 'Sticker/Ticket en Whats'), ('5', 'Etiquetas Barrido'), ('6', 'Priorización'), ('7', 'Registro de Actividades')], max_length=2, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='ParrillasEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.today)),
                ('objetivo', models.CharField(blank=True, choices=[('1', 'Producto'), ('2', 'Promoción'), ('3', 'RRHH'), ('4', 'Relaciones Públicas'), ('5', 'Campaña'), ('6', 'Servicio')], max_length=2, null=True)),
                ('tema', models.CharField(blank=True, max_length=200)),
                ('copy', models.CharField(blank=True, max_length=300)),
                ('frase', models.CharField(blank=True, max_length=500)),
                ('nuevo', models.BinaryField(default=False)),
                ('republicacion', models.BinaryField(default=False)),
                ('link', models.CharField(max_length=500)),
                ('tipos_contenido', models.CharField(blank=True, choices=[('1', 'Video'), ('2', 'Carrete'), ('3', 'Reel'), ('4', 'Frase'), ('3', 'Publicación'), ('4', 'Historia'), ('3', 'Publicación/Historia')], max_length=2, null=True)),
                ('plataforma', models.CharField(blank=True, choices=[('1', 'Facebook'), ('2', 'Instagram'), ('3', 'Ligado'), ('4', 'YouTube'), ('4', 'TikTok')], max_length=2, null=True)),
                ('elaborado', models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'DO'), ('groups__name', 'creativo'), ('groups__name', 'cliente'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elaborado', to='auth.user')),
                ('parrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.parrillas')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets')),
            ],
        ),
        migrations.DeleteModel(
            name='Parrilas',
        ),
    ]
