# Generated by Django 4.0 on 2023-05-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_rename_parrillasentry_parrillasentries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrillas',
            name='tipo_error',
        ),
    ]
