# Generated by Django 4.0 on 2023-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_alter_parrillas_mes_alter_parrillasentries_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrillasentries',
            name='copy',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
