# Generated by Django 4.0 on 2023-05-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_alter_parrillasentries_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrillasentries',
            name='nuevo',
        ),
        migrations.RemoveField(
            model_name='parrillasentries',
            name='republicacion',
        ),
    ]
