# Generated by Django 4.0 on 2023-05-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0033_remove_parrillasentries_nuevo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='apoyo',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'DO'), ('groups__name', 'DO'), ('groups__name', 'creativo'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoyo', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='encargado',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'DG'), ('groups__name', 'DO'), ('groups__name', 'creativo'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to='auth.user'),
        ),
    ]
